theme: jekyll-theme-minimal
title: Red and Blue Team analysis
description: The goal of this page is to hack boxes, and also look at the IOCs from a blue team perspective in order to give the full idea of what a compromise may look like.
